const ADMIN_AVATAR = process.env.ADMIN_AVATAR;
const USER_AVATAR = process.env.USER_AVATAR;
const TESTIMONIAL_AVATAR = process.env.TESTIMONIAL_AVATAR;
const NEWS_AVATAR = process.env.NEWS_AVATAR;

module.exports = {
  ADMIN_AVATAR,
  USER_AVATAR,
  TESTIMONIAL_AVATAR,
  NEWS_AVATAR,
};
